## 1. 파이썬 파일 처리

In [4]:
sample_file = 'C:\\Users\\1\\Desktop\\강의자료\\2학기\\빅데이터\\4주차\\data\\sample.txt'

In [5]:
# 파일을 open하여 전체 내용을 읽어서 출력
with open(sample_file, mode='rt') as f:
    content = f.read()
    print(content)
print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

----- 끝 -----

In [6]:
# 파일을 open하고 한 줄씩 읽어서 출력하기 : readlines(), readline()
with open(sample_file, 'r') as f:
    lines = f.readlines()
    print(lines)


print("----- 끝 -----")

['나의 속도로\n', '\n', '조금 늦어도 괜찮다.\n', '남들과 같은 길을 갈 필요도 없다.\n', '\n', '오늘 배운 것 하나,\n', '오늘 해결한 문제 하나가\n', '조금씩 나의 실력이 된다.\n', '\n', '결과가 보이지 않는 날에도\n', '나는 앞으로 가고 있다.\n', '\n', '빠르게 가는 것보다\n', '멈추지 않는 것이 중요하다.\n', '\n', '오늘의 작은 한 걸음이\n', '내일의 나를 만든다.\n', '\n', '나는 늦은 것이 아니라\n', '나의 속도로 가고 있다.\n']
----- 끝 -----

In [7]:
# 파일을 open하고 한 줄씩 읽어서 출력하기 : readlines(), readline()
with open(sample_file, 'r') as f:
    line = f.readline()
    while line:
        print(line, end="")
        line = f. readline()

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

In [8]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, 'r') as f:
    for line in f:
        print(line, end="")

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [9]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob
txt_file_pattern = "C:\\Users\\1\\Desktop\\강의자료\\2학기\\빅데이터\\4주차\\data\\*.txt"
files = glob.glob(txt_file_pattern)
print(files)
for file in files:
    print(file)
    with open(file, "r") as f:
        print(f.read())
print(" -----끝---- ")

['C:\\Users\\1\\Desktop\\강의자료\\2학기\\빅데이터\\4주차\\data\\hello.txt', 'C:\\Users\\1\\Desktop\\강의자료\\2학기\\빅데이터\\4주차\\data\\sample.txt', 'C:\\Users\\1\\Desktop\\강의자료\\2학기\\빅데이터\\4주차\\data\\score.txt']
C:\Users\1\Desktop\강의자료\2학기\빅데이터\4주차\data\hello.txt
안녕하세요
hello
내용을 추가합니다.
저장하는 문서 이름,  'w' 대신 'a'를 사용합니다.

C:\Users\1\Desktop\강의자료\2학기\빅데이터\4주차\data\sample.txt
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

C:\Users\1\Desktop\강의자료\2학기\빅데이터\4주차\data\score.txt
90
100
85
95
 -----끝----

## 2. 파이썬 문자열 다루기

In [10]:
# 양쪽 공백 제거
text=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
text.strip()

'작은 일에 성실한 사람은      큰일에도 성실하고'

In [11]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text=text.strip('.')

In [12]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text.strip(",").strip(".")

'작은 일에 성실한 사람은, 큰일에도 성실하고'

In [13]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
numbers.split(".")

['1', ' 2', ' 3', ' 4', ' 5', ' 6']

## 3. 판다스로 데이터 가져오기

In [43]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in C:\Users\1\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\1\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\1\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\1\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\1\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [44]:
import pandas as pd

In [49]:
# 타이타닉 데이터 가져오기
titanic_url = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
sample_df = pd.read_csv(titanic_url)

In [50]:

sample_df = pd.read_csv(titanic_data, sep="\t")
sample_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 연습용 sample_data.csv 로딩하기
sample_df.to_csv('C:\\Users\\1\\Desktop\\강의자료\\2학기\\빅데이터\\4주차\\data\\sample_data_copy.csv', index=False)

In [51]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기

t_df = pd.read_csv(titanic_data, sep="\t")
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [52]:

sample_file = 'data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [129]:
# 연습용 sample_data.csv 로딩하기
sample_file = 'data/sample_data.csv'

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [130]:
# 앞부분 확인
t_df.head(10)

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
52,52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
122,122,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
9,9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
108,108,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S
50,50,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
151,151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
4,4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
90,90,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S
59,59,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN

In [131]:
# 뒷부분 확인
t_df.tail(10)

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
80,80,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
85,85,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
93,93,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
99,99,102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
105,105,108,1,3,"Moss, Mr. Albert Johan",male,NaN,0,0,312991,7.7750,NaN,S
107,107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [132]:
# 데이터 개수/형태 확인
t_df.shape

(152, 13)

In [133]:
#데이터의 기본 통계치 보기
t_df.info()

<class 'pandas.DataFrame'>
Index: 152 entries, 94 to 138
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        152 non-null    int64
 1   passengerid  152 non-null    int64
 2   survived     152 non-null    int64
 3   pclass       152 non-null    int64
 4   name         152 non-null    str
 5   sex          152 non-null    str
 6   age          123 non-null    float64
 7   sibsp        152 non-null    int64
 8   parch        152 non-null    int64
 9   ticket       152 non-null    str
 10  fare         152 non-null    float64
 11  cabin        31 non-null     str
 12  embarked     151 non-null    str
dtypes: float64(2), int64(6), str(5)
memory usage: 22.8 KB

In [134]:
# 데이터 구성 정보 확인하기
t_df.describe()

,index,passengerid,survived,pclass,age,sibsp,parch,fare
count,152.000000,152.000000,152.000000,152.000000,123.000000,152.000000,152.000000,152.000000
mean,75.500000,78.486842,0.348684,2.407895,27.880732,0.631579,0.407895,28.643145
std,44.022721,44.113788,0.478129,0.800292,14.566751,1.065312,0.879157,39.779242
min,0.000000,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,37.750000,40.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.044800
50%,75.500000,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.479150
75%,113.250000,116.250000,1.000000,3.000000,35.000000,1.000000,0.000000,31.275000
max,151.000000,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [135]:
# 타이타닉 데이터 구조 및 구성 확인하기\
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nAME    7 non-null      str
 1   aGE     5 non-null      float64
 2   gENDER  7 non-null      str
 3   cITY    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 448.0 bytes

### 4-2. 컬럼명과 인덱스 정리

In [136]:
# 데이터프레임 복사하기 (deep copy)
sample_backup_df = sample_df.copy()
sample_backup_df

      nAME   aGE gENDER         cITY
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [137]:
# 열 이름 변경하기 : 모두 소문자로 변경
new_cols = []
for col in sample_df.columns:
    new_cols.append(col.lower())
sample_df.columns = new_cols
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [138]:
# index 확인
sample_backup_df.index

RangeIndex(start=0, stop=7, step=1)

###숙제

In [139]:
# 컬럼명으노첫글자는 소문자로, 나머지는 대문자로 수정

sample_df = sample_df.rename(columns=lambda x: x[0].lower() + x[1:].upper())

print(sample_df.columns)

Index(['nAME', 'aGE', 'gENDER', 'cITY'], dtype='str')

In [140]:
sample_df = sample_df.rename(columns=str.lower)
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [141]:
sample_df = sample_df.rename(columns=str.capitalize)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [142]:
# index를 0부터 순서대로 assign 되도록 reset하기
t_df = t_df.reset_index(drop=True)
t_df

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
1,52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
2,122,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
3,9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
4,108,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
148,119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
149,124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
150,126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
151,138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [143]:
t_df = t_df.rename(columns=str.lower)
t_df.head()

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
1,52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
2,122,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
3,9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
4,108,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S

In [144]:
# index를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df = t_df.reset_index()
t_df

,level_0,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
1,1,52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
2,2,122,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
3,3,9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
4,4,108,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
148,148,119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
149,149,124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
150,150,126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
151,151,138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

### 4-3. 데이터 정렬

In [123]:
# 'age' 기준으로 정렬
t_df.sort_values(by='age')

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
76,76,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
5,5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
14,14,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
117,117,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
41,41,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [124]:
# 'age' 기준으로 내림차순으로 정렬
t_df.sort_values(by='age', ascending=False).head()

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
114,114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
31,31,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
92,92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S

In [125]:
# 'age', 'pclass'를 기준으로 정렬
t_df.sort_values(by=['pclass', 'age'])

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
25,25,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
134,134,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S
100,100,103,0,1,"White, Mr. Richard Frasar",male,21.0,0,1,35281,77.2875,D26,S
149,149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
86,86,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

###숙제2

In [128]:
t_df = t_df.sort_values(by='age', ascending=False)   # 1. 2순위 기준(age 내림차순) 먼저 정렬
t_df = t_df.sort_values(by='pclass', ascending=True)  # 2. 1순위 기준(pclass 오름차순) 나중에 정렬

t_df.head()

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
52,52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
122,122,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
9,9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
108,108,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S

In [127]:
# index를 기준으로 정렬
t_df. sort_index()

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [79]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [80]:
# 행 지정 -> 슬라이싱
score_df[2:3]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [81]:
# 열 접근
score_df['이름']

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [82]:
score_df[['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [83]:
# 특정 (행,열)의 데이터 접근
score_df[1:2][['이름','국어']]

    이름   국어
1  이순신  100

In [84]:
# 인덱서 이용 : 레이블(이름) 인덱서
# 행 접근
score_df . loc [1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [85]:
# 열 접근
score_df.loc[:,['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [86]:
# (행,열) 접근
score_df.loc[:1,'이름':'국어']

    이름   국어
0  정약용   70
1  이순신  100

In [87]:
# (행,열) 접근
score_df.loc[1, '국어']

np.int64(100)

In [88]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[:1]

    이름  국어  영어   수학
0  정약용  70  80  100

In [76]:
# 열 접근
score_df.iloc[:,1:3]

    국어   영어
0   70   80
1  100   80
2   90   95
3   85  100

In [77]:
# (행,열) 접근
score_df.iloc[:2,1:3]

    국어  영어
0   70  80
1  100  80

In [78]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [ ]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df['수학'] >= 90]

In [79]:
# 인덱서 방식으로 행 추출
score_df[(score_df['국어'] >= 90) & (score_df['수학'] >= 90)]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [82]:
# (행,열) 데이터 추출
score_df[(score_df.이름.isin(['정약용','이순신']))]

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70

In [83]:
# (행,열) 데이터 추출
score_df.loc[score_df.수학 >= 90, ['이름', '수학']]

    이름   수학
0  정약용  100
2  이율곡   90
3  홍길동   90

In [84]:
# 열 데이터에 조건 지정
score_df.loc[:,score_df.columns !='영어']

    이름   국어   수학
0  정약용   70  100
1  이순신  100   70
2  이율곡   90   90
3  홍길동   85   90

In [85]:
# 열 데이터에 조건 지정
score_df.loc[:, score_df.dtypes == 'int']

    국어   영어   수학
0   70   80  100
1  100   80   70
2   90   95   90
3   85  100   90

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [86]:
sample_file = 'C:\\Users\\1\\Desktop\\강의자료\\2학기\\빅데이터\\4주차\\data\\sample.txt'

In [ ]:
# 샘플 파일 로딩

In [ ]:
# 지역별 판매 기록의 개수

In [ ]:
# 상품별 판매 기록의 개수와 비율

In [ ]:
# 지역과 상품의 조합별 판매 기록 개수

In [ ]:
# 지역별 총매출

In [ ]:
# 상품별 평균 매출

In [ ]:
# 지역별 판매수량의 합계와 매출의 합계

In [ ]:
# 지역과 상품별 평균 매출

In [ ]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시

## 4-6. 직접해보기

In [38]:
import pandas as pd

titanic_url = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(titanic_url)

titanic_df = pd.read_csv(titanic_data, sep="\t")
titanic_df.head()
# 2. 슬라이싱 실행 (이제 정상 작동합니다!)
titanic_df[0:5]
titanic_df[0:1]
titanic_df[:3]
titanic_df[::-1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [39]:
titanic_df[:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [40]:
#173
len(titanic_df.columns)

12

In [41]:
titanic_df[titanic_df.columns[0]]

0        1
1        2
2        3
3        4
4        5
      ...
151    152
152    153
153    154
154    155
155    156
Name: PassengerId, Length: 156, dtype: int64

In [42]:
titanic_df[titanic_df.columns[11]]

0      S
1      C
2      S
3      S
4      S
      ..
151    S
152    S
153    S
154    S
155    C
Name: Embarked, Length: 156, dtype: str

In [44]:
age=titanic_df['Age']
print(type(age))

<class 'pandas.Series'>

In [47]:
titanic_df['Age']
titanic_df.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: Age, Length: 156, dtype: float64

In [48]:
#175   
print(titanic_df[titanic_df.columns[0]][0])
print(titanic_df['Age'][0])
print(titanic_df[titanic_df.columns[0]][2])
print(titanic_df[titanic_df.columns[-1]][0])
type(titanic_df[titanic_df.columns[0]][0])

1
22.0
3
S

numpy.int64

In [49]:
titanic_df[titanic_df.columns[0]][2:6]
titanic_df[titanic_df.columns[0]][ :- 1]
titanic_df[titanic_df.columns[0]][ :: 3]
titanic_df[titanic_df.columns[0]][-1:]
titanic_df[titanic_df.columns[0]][ ::- 1]

155    156
154    155
153    154
152    153
151    152
      ...
4        5
3        4
2        3
1        2
0        1
Name: PassengerId, Length: 156, dtype: int64

In [51]:
titanic_df[['Pclass','Name','Sex']]

titanic_df[[titanic_df.columns[2],titanic_df.columns[3],titanic_df.columns[4]]]

     Pclass                                               Name     Sex
0         3                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         3                             Heikkinen, Miss. Laina  female
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4         3                           Allen, Mr. William Henry    male
..      ...                                                ...     ...
151       1                  Pears, Mrs. Thomas (Edith Wearne)  female
152       3                                   Meo, Mr. Alfonzo    male
153       3                    van Billiard, Mr. Austin Blyler    male
154       3                              Olsen, Mr. Ole Martin    male
155       1                        Williams, Mr. Charles Duane    male

[156 rows x 3 columns]

In [52]:
titanic_df[[titanic_df.columns[2],titanic_df.columns[3],titanic_df.columns[4]]][2:15:3]

    Pclass                                               Name     Sex
2        3                             Heikkinen, Miss. Laina  female
5        3                                   Moran, Mr. James    male
8        3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
11       1                           Bonnell, Miss. Elizabeth  female
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female

In [53]:
print(titanic_df[titanic_df.columns[0]][0])
print(titanic_df[titanic_df.columns[0]][2])
#print(titanic_df[titanic_df.columns[0]][-1])
type(titanic_df[titanic_df.columns[0]][0])

1
3

numpy.int64

In [54]:
titanic_df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [55]:
titanic_df.loc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [56]:
titanic_df.loc[0:10:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

In [57]:
titanic_df.loc[0:'Age']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [59]:
#179   
titanic_df.loc[:, ['Age', 'Sex']]

      Age     Sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
151  22.0  female
152  55.5    male
153  40.5    male
154   NaN    male
155  51.0    male

[156 rows x 2 columns]

In [ ]:

titanic_df.loc[3:7, ['Age', 'Sex']]

    Age     Sex
3  35.0  female
4  35.0    male
5   NaN    male
6  54.0    male
7   2.0    male

In [64]:
titanic_df.loc[2:5, 'Survived':'Age']

,Survived,Pclass,Name,Sex,Age
2,1,3,"Heikkinen, Miss. Laina",female,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,0,3,"Allen, Mr. William Henry",male,35.0
5,0,3,"Moran, Mr. James",male,NaN

In [65]:
titanic_df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [66]:
titanic_df.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#181
titanic_df.iloc[0:10:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [68]:
titanic_df.iloc[:, [0, 2]]

     PassengerId  Pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
151          152       1
152          153       3
153          154       3
154          155       3
155          156       1

[156 rows x 2 columns]

In [69]:
titanic_df.iloc[1:5, [0, 2]]

   PassengerId  Pclass
1            2       1
2            3       3
3            4       1
4            5       3

In [70]:
titanic_df.iloc[1:5, 1:4]

   Survived  Pclass                                               Name
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry

In [72]:
titanic_df.pivot_table(index='Pclass', columns='Sex', values='Survived')

Sex       female      male
Pclass
1       1.000000  0.142857
2       0.916667  0.166667
3       0.571429  0.131148

In [ ]:
#181
titanic_df.iloc[0:10:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [74]:
titanic_df.iloc[:, [0, 2]]

     PassengerId  Pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
151          152       1
152          153       3
153          154       3
154          155       3
155          156       1

[156 rows x 2 columns]

In [75]:
titanic_df.iloc[1:5, [0, 2]]

   PassengerId  Pclass
1            2       1
2            3       3
3            4       1
4            5       3

In [ ]:
#183
import numpy as np

titanic_df.pivot_table(index='Pclass', columns='Sex', values='Survived', aggfunc=np.mean)

Sex       female      male
Pclass
1       1.000000  0.142857
2       0.916667  0.166667
3       0.571429  0.131148

In [77]:
titanic_df.pivot_table(index='Pclass', columns='Sex', values='Survived', aggfunc=np.sum)

Sex     female  male
Pclass
1            9     3
2           11     3
3           20     8